import { AfterViewInit, ElementRef, EventEmitter, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { Control } from 'ol/control';
import { Interaction } from 'ol/interaction';
import Map from 'ol/Map';
import MapBrowserEvent from 'ol/MapBrowserEvent';
import MapEvent from 'ol/MapEvent';
import { ObjectEvent } from 'ol/Object';
import RenderEvent from 'ol/render/Event';
import * as i0 from "@angular/core";
export declare class MapComponent implements OnInit, AfterViewInit, OnChanges {
    private readonly host;
    instance: Map;
    componentType: string;
    width: string;
    height: string;
    pixelRatio: number;
    keyboardEventTarget: HTMLElement | string;
    loadTilesWhileAnimating: boolean;
    loadTilesWhileInteracting: boolean;
    logo: string | boolean;
    renderer: 'canvas' | 'webgl';
    props: string[];
    readonly olClick: EventEmitter<MapBrowserEvent>;
    readonly dblClick: EventEmitter<MapBrowserEvent>;
    readonly moveStart: EventEmitter<MapEvent>;
    readonly moveEnd: EventEmitter<MapEvent>;
    readonly pointerDrag: EventEmitter<MapBrowserEvent>;
    readonly pointerMove: EventEmitter<MapBrowserEvent>;
    readonly onpostrender: EventEmitter<RenderEvent>;
    readonly postRender: EventEmitter<MapEvent>;
    readonly onprerender: EventEmitter<RenderEvent>;
    readonly propertyChange: EventEmitter<ObjectEvent>;
    readonly singleClick: EventEmitter<MapBrowserEvent>;
    controls: Array<Control>;
    interactions: Array<Interaction>;
    constructor(host: ElementRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngAfterViewInit(): void;
    static ɵfac: i0.ɵɵFactoryDef<MapComponent, never>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<MapComponent, "map-map", never, { "width": "width"; "height": "height"; "pixelRatio": "pixelRatio"; "keyboardEventTarget": "keyboardEventTarget"; "loadTilesWhileAnimating": "loadTilesWhileAnimating"; "loadTilesWhileInteracting": "loadTilesWhileInteracting"; "logo": "logo"; "renderer": "renderer"; }, { "olClick": "olClick"; "dblClick": "dblClick"; "moveStart": "moveStart"; "moveEnd": "moveEnd"; "pointerDrag": "pointerDrag"; "pointerMove": "pointerMove"; "onpostrender": "onpostrender"; "postRender": "postRender"; "onprerender": "onprerender"; "propertyChange": "propertyChange"; "singleClick": "singleClick"; }, never, ["*"]>;
}
