import { EventEmitter, OnDestroy, OnInit } from '@angular/core';
import { Collection, Feature } from 'ol';
import { Condition } from 'ol/events/condition';
import GeometryType from 'ol/geom/GeometryType';
import { Draw } from 'ol/interaction';
import { DrawEvent, GeometryFunction } from 'ol/interaction/Draw';
import { Vector } from 'ol/source';
import { Style } from 'ol/style';
import { StyleFunction } from 'ol/style/Style';
import { MapComponent } from '../map.component';
import * as i0 from "@angular/core";
export declare class DrawInteractionComponent implements OnInit, OnDestroy {
    readonly map: MapComponent;
    instance: Draw;
    clickTolerance?: number;
    features?: Collection<Feature>;
    source?: Vector;
    snapTolerance?: number;
    type: GeometryType;
    maxPoints?: number;
    minPoints?: number;
    finishCondition?: Condition;
    style?: Style | Array<Style> | StyleFunction;
    geometryFunction?: GeometryFunction;
    geometryName?: string;
    condition?: Condition;
    freehandCondition?: Condition;
    freehand?: boolean;
    wrapX?: boolean;
    readonly olChange: EventEmitter<DrawEvent>;
    readonly olChangeActive: EventEmitter<DrawEvent>;
    readonly drawEnd: EventEmitter<DrawEvent>;
    readonly drawStart: EventEmitter<DrawEvent>;
    readonly propertyChange: EventEmitter<DrawEvent>;
    constructor(map: MapComponent);
    ngOnInit(): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDef<DrawInteractionComponent, never>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<DrawInteractionComponent, "map-interaction-draw", never, { "clickTolerance": "clickTolerance"; "features": "features"; "source": "source"; "snapTolerance": "snapTolerance"; "type": "type"; "maxPoints": "maxPoints"; "minPoints": "minPoints"; "finishCondition": "finishCondition"; "style": "style"; "geometryFunction": "geometryFunction"; "geometryName": "geometryName"; "condition": "condition"; "freehandCondition": "freehandCondition"; "freehand": "freehand"; "wrapX": "wrapX"; }, { "olChange": "olChange"; "olChangeActive": "olChangeActive"; "drawEnd": "drawEnd"; "drawStart": "drawStart"; "propertyChange": "propertyChange"; }, never, never>;
}
