import { EventEmitter, OnDestroy, OnInit } from '@angular/core';
import { Collection, Feature } from 'ol';
import { Condition } from 'ol/events/condition';
import { Modify } from 'ol/interaction';
import { ModifyEvent } from 'ol/interaction/Modify';
import { Vector } from 'ol/source';
import { Style } from 'ol/style';
import { StyleFunction } from 'ol/style/Style';
import { MapComponent } from '../map.component';
import * as i0 from "@angular/core";
export declare class ModifyInteractionComponent implements OnInit, OnDestroy {
    readonly map: MapComponent;
    instance: Modify;
    condition?: Condition;
    deleteCondition?: Condition;
    pixelTolerance?: number;
    style?: Style | Array<Style> | StyleFunction;
    features: Collection<Feature>;
    wrapX?: boolean;
    source?: Vector;
    readonly modifyEnd: EventEmitter<ModifyEvent>;
    readonly modifyStart: EventEmitter<ModifyEvent>;
    readonly olChange: EventEmitter<ModifyEvent>;
    readonly olChangeActive: EventEmitter<ModifyEvent>;
    readonly propertyChange: EventEmitter<ModifyEvent>;
    constructor(map: MapComponent);
    ngOnInit(): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDef<ModifyInteractionComponent, never>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<ModifyInteractionComponent, "map-interaction-modify", never, { "condition": "condition"; "deleteCondition": "deleteCondition"; "pixelTolerance": "pixelTolerance"; "style": "style"; "features": "features"; "wrapX": "wrapX"; "source": "source"; }, { "modifyEnd": "modifyEnd"; "modifyStart": "modifyStart"; "olChange": "olChange"; "olChangeActive": "olChangeActive"; "propertyChange": "propertyChange"; }, never, never>;
}
