import { EventEmitter, OnDestroy, OnInit } from '@angular/core';
import { Collection, Feature } from 'ol';
import { Condition } from 'ol/events/condition';
import { Select } from 'ol/interaction';
import { FilterFunction, SelectEvent } from 'ol/interaction/Select';
import { Layer } from 'ol/layer';
import { Style } from 'ol/style';
import { StyleFunction } from 'ol/style/Style';
import { MapComponent } from '../map.component';
import * as i0 from "@angular/core";
export declare class SelectInteractionComponent implements OnInit, OnDestroy {
    readonly map: MapComponent;
    instance: Select;
    addCondition?: Condition;
    condition?: Condition;
    layers?: Array<Layer> | ((layer: Layer) => boolean);
    style?: Style | Array<Style> | StyleFunction;
    removeCondition?: Condition;
    toggleCondition?: Condition;
    multi?: boolean;
    features?: Collection<Feature>;
    filter?: FilterFunction;
    wrapX?: boolean;
    readonly olChange: EventEmitter<SelectEvent>;
    readonly olSelect: EventEmitter<SelectEvent>;
    readonly propertyChange: EventEmitter<SelectEvent>;
    constructor(map: MapComponent);
    ngOnInit(): void;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDef<SelectInteractionComponent, never>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<SelectInteractionComponent, "map-interaction-select", never, { "addCondition": "addCondition"; "condition": "condition"; "layers": "layers"; "style": "style"; "removeCondition": "removeCondition"; "toggleCondition": "toggleCondition"; "multi": "multi"; "features": "features"; "filter": "filter"; "wrapX": "wrapX"; }, { "olChange": "olChange"; "olSelect": "olSelect"; "propertyChange": "propertyChange"; }, never, never>;
}
