import { AfterContentInit, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { ProjectionLike } from 'ol/proj';
import { TileSourceEvent } from 'ol/source/Tile';
import WMTS from 'ol/source/WMTS';
import WMTSRequestEncoding from 'ol/source/WMTSRequestEncoding';
import { LoadFunction } from 'ol/Tile';
import WMTSTileGrid from 'ol/tilegrid/WMTS';
import { LayerTileComponent } from '../layers/layertile.component';
import { TileGridWMTSComponent } from '../tilegridwmts.component';
import { SourceComponent } from './source.component';
import * as i0 from "@angular/core";
export declare class SourceTileWMTSComponent extends SourceComponent implements AfterContentInit, OnChanges {
    instance: WMTS;
    cacheSize?: number;
    crossOrigin?: string;
    tileGrid: WMTSTileGrid;
    projection: ProjectionLike;
    reprojectionErrorThreshold?: number;
    requestEncoding?: WMTSRequestEncoding | string;
    layer: string;
    style: string;
    tileClass?: any;
    tilePixelRatio?: number;
    version?: string;
    format?: string;
    matrixSet: string;
    dimensions?: any;
    url?: string;
    tileLoadFunction?: LoadFunction;
    urls?: Array<string>;
    wrapX?: boolean;
    props: string[];
    readonly tileLoadStart: EventEmitter<TileSourceEvent>;
    readonly tileLoadEnd: EventEmitter<TileSourceEvent>;
    readonly tileLoadError: EventEmitter<TileSourceEvent>;
    tileGridWMTS: TileGridWMTSComponent;
    constructor(layer: LayerTileComponent);
    ngOnChanges(changes: SimpleChanges): void;
    setLayerSource(): void;
    ngAfterContentInit(): void;
    static ɵfac: i0.ɵɵFactoryDef<SourceTileWMTSComponent, [{ host: true; }]>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<SourceTileWMTSComponent, "map-source-tilewmts", never, { "cacheSize": "cacheSize"; "crossOrigin": "crossOrigin"; "tileGrid": "tileGrid"; "projection": "projection"; "reprojectionErrorThreshold": "reprojectionErrorThreshold"; "requestEncoding": "requestEncoding"; "layer": "layer"; "style": "style"; "tileClass": "tileClass"; "tilePixelRatio": "tilePixelRatio"; "version": "version"; "format": "format"; "matrixSet": "matrixSet"; "dimensions": "dimensions"; "url": "url"; "tileLoadFunction": "tileLoadFunction"; "urls": "urls"; "wrapX": "wrapX"; }, { "tileLoadStart": "tileLoadStart"; "tileLoadEnd": "tileLoadEnd"; "tileLoadError": "tileLoadError"; }, ["tileGridWMTS"], ["*"]>;
}
